/*
 * GOLDEN-API
 * Trazadera Golden API
 *
 * OpenAPI spec version: 16-SNAPSHOT
 * Contact: support@trazadera.com 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.trazadera.golden.restclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Represents a record delete request
 */
@Schema(description = "Represents a record delete request")

public class GoldenDeleteRequestDto {
  @SerializedName("audit")
  private Boolean audit = null;

  @SerializedName("recordId")
  private String recordId = null;

  public GoldenDeleteRequestDto audit(Boolean audit) {
    this.audit = audit;
    return this;
  }

   /**
   * Flag to return audit information. By default is false.
   * @return audit
  **/
  @Schema(required = true, description = "Flag to return audit information. By default is false.")
  public Boolean isAudit() {
    return audit;
  }

  public void setAudit(Boolean audit) {
    this.audit = audit;
  }

  public GoldenDeleteRequestDto recordId(String recordId) {
    this.recordId = recordId;
    return this;
  }

   /**
   * Record identifier.
   * @return recordId
  **/
  @Schema(required = true, description = "Record identifier.")
  public String getRecordId() {
    return recordId;
  }

  public void setRecordId(String recordId) {
    this.recordId = recordId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoldenDeleteRequestDto goldenDeleteRequestDto = (GoldenDeleteRequestDto) o;
    return Objects.equals(this.audit, goldenDeleteRequestDto.audit) &&
        Objects.equals(this.recordId, goldenDeleteRequestDto.recordId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audit, recordId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoldenDeleteRequestDto {\n");
    
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
