/*
 * GOLDEN-API
 * Trazadera Golden API
 *
 * OpenAPI spec version: 16-SNAPSHOT
 * Contact: support@trazadera.com 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.trazadera.golden.restclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Represents a response to import resources.
 */
@Schema(description = "Represents a response to import resources.")

public class ResourceImportResponseDto {
  @SerializedName("imported")
  private Integer imported = null;

  @SerializedName("total")
  private Integer total = null;

  @SerializedName("errors")
  private List<String> errors = null;

  @SerializedName("messages")
  private List<String> messages = null;

  public ResourceImportResponseDto imported(Integer imported) {
    this.imported = imported;
    return this;
  }

   /**
   * Total number of imported resources.
   * @return imported
  **/
  @Schema(description = "Total number of imported resources.")
  public Integer getImported() {
    return imported;
  }

  public void setImported(Integer imported) {
    this.imported = imported;
  }

  public ResourceImportResponseDto total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Total number of resources.
   * @return total
  **/
  @Schema(description = "Total number of resources.")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public ResourceImportResponseDto errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public ResourceImportResponseDto addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * List of errors. If HTTP response represents an error (4xx or 5xx) this will contain a list of errors. Otherwise, not present.
   * @return errors
  **/
  @Schema(description = "List of errors. If HTTP response represents an error (4xx or 5xx) this will contain a list of errors. Otherwise, not present.")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public ResourceImportResponseDto messages(List<String> messages) {
    this.messages = messages;
    return this;
  }

  public ResourceImportResponseDto addMessagesItem(String messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<String>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Optional informational messages. If present, the request was successful and response code will be 2xx.
   * @return messages
  **/
  @Schema(description = "Optional informational messages. If present, the request was successful and response code will be 2xx.")
  public List<String> getMessages() {
    return messages;
  }

  public void setMessages(List<String> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceImportResponseDto resourceImportResponseDto = (ResourceImportResponseDto) o;
    return Objects.equals(this.imported, resourceImportResponseDto.imported) &&
        Objects.equals(this.total, resourceImportResponseDto.total) &&
        Objects.equals(this.errors, resourceImportResponseDto.errors) &&
        Objects.equals(this.messages, resourceImportResponseDto.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imported, total, errors, messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceImportResponseDto {\n");
    
    sb.append("    imported: ").append(toIndentedString(imported)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
