/*
 * GOLDEN-API
 * Trazadera Golden API
 *
 * OpenAPI spec version: 15
 * Contact: support@trazadera.com 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.trazadera.golden.restclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.trazadera.golden.restclient.model.Principal;
import com.trazadera.golden.restclient.model.TaskInstanceDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;import java.util.Map;
import java.util.List;
import java.util.Map;
/**
 * Represents a task instance.
 */
@Schema(description = "Represents a task instance.")

public class TaskInstanceResponseDto {
  @SerializedName("task")
  private TaskInstanceDto task = null;

  @SerializedName("principals")
  private Map<String, Principal> principals = null;

  @SerializedName("errors")
  private List<String> errors = null;

  @SerializedName("messages")
  private List<String> messages = null;

  public TaskInstanceResponseDto task(TaskInstanceDto task) {
    this.task = task;
    return this;
  }

   /**
   * Get task
   * @return task
  **/
  @Schema(description = "")
  public TaskInstanceDto getTask() {
    return task;
  }

  public void setTask(TaskInstanceDto task) {
    this.task = task;
  }

  public TaskInstanceResponseDto principals(Map<String, Principal> principals) {
    this.principals = principals;
    return this;
  }

  public TaskInstanceResponseDto putPrincipalsItem(String key, Principal principalsItem) {
    if (this.principals == null) {
      this.principals = new HashMap<String, Principal>();
    }
    this.principals.put(key, principalsItem);
    return this;
  }

   /**
   * Map of principals. Handy to decorate the user identifiers.
   * @return principals
  **/
  @Schema(description = "Map of principals. Handy to decorate the user identifiers.")
  public Map<String, Principal> getPrincipals() {
    return principals;
  }

  public void setPrincipals(Map<String, Principal> principals) {
    this.principals = principals;
  }

  public TaskInstanceResponseDto errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public TaskInstanceResponseDto addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * List of errors. If HTTP response represents an error (4xx or 5xx) this will contain a list of errors. Otherwise, not present.
   * @return errors
  **/
  @Schema(description = "List of errors. If HTTP response represents an error (4xx or 5xx) this will contain a list of errors. Otherwise, not present.")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public TaskInstanceResponseDto messages(List<String> messages) {
    this.messages = messages;
    return this;
  }

  public TaskInstanceResponseDto addMessagesItem(String messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<String>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Optional informational messages. If present, the request was successful and response code will be 2xx.
   * @return messages
  **/
  @Schema(description = "Optional informational messages. If present, the request was successful and response code will be 2xx.")
  public List<String> getMessages() {
    return messages;
  }

  public void setMessages(List<String> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskInstanceResponseDto taskInstanceResponseDto = (TaskInstanceResponseDto) o;
    return Objects.equals(this.task, taskInstanceResponseDto.task) &&
        Objects.equals(this.principals, taskInstanceResponseDto.principals) &&
        Objects.equals(this.errors, taskInstanceResponseDto.errors) &&
        Objects.equals(this.messages, taskInstanceResponseDto.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(task, principals, errors, messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskInstanceResponseDto {\n");
    
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    principals: ").append(toIndentedString(principals)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
